### ISSUE TITLE
Quick Card: On design confirmation page, there are two periods in a sentence (typo)

### ISSUE THREAD

**Issue by harry-pabla** [Pablabs-MFGSoftTech/AllCard#1]
On the design confirmation page, the text blob at the bottom has two periods after the first sentence.

![image](https://user-images.githubusercontent.com/37029242/36940303-6e40aec2-1f0e-11e8-8e6c-42e45f1b1d93.png)

**Comment by AMassani** [comment]
Fixed

**Comment by harry-pabla** [comment]
Verified the extra period has been removed.

Verified on IE 11.0.9600.18231

![image](https://user-images.githubusercontent.com/37029242/36951173-7e3144f2-1fce-11e8-97bb-dbfa5b7605a6.png)
